plugins {
  id 'java-library'
  id 'scala'
  id 'maven-publish'
  id 'signing'
  id 'org.podval.conventions'
  id 'org.podval.conventions.publish'
}

description = 'Pulumi tooling'
group = 'org.podval.tools'

podvalPublish {
  gitHubRepository = 'dubinsky/pulumi'
  name = 'Podval Pulumi'
  inceptionYear = '2023'
}

dependencies {
  compileOnly 'org.virtuslab:besom-core_3:0.5.1'
  compileOnly 'org.virtuslab:besom-gcp_3:9.0.0-core.0.5'
  compileOnly 'org.virtuslab:besom-cloudflare_3:6.20.0-core.0.5'
}
